flags: {}
extra-package-dbs: []
packages:
- introduction
- introduction-test
extra-deps:
- location: /home/syd/validity/validity-bytestring
  extra-dep: true
- genvalidity-0.2.0.4
- genvalidity-containers-0.1.0.2
- genvalidity-hspec-0.2.0.5
- genvalidity-text-0.1.0.1
- validity-0.3.0.4
- validity-containers-0.1.0.1
- validity-text-0.1.0.1
resolver: lts-7.1
